// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BonusStats = { dora: number, uraDora: number, akaDora: number, winsWithDora: number, winsWithUraDora: number, winsWithAkaDora: number, doraHitRate: number, uraDoraHitRate: number, akaDoraHitRate: number, };
