// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallStats = { total: number, chi: number, pon: number, openKan: number, closedKan: number, addedKan: number, nuki: number, };
