// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountBucket } from "./CountBucket";
import type { DealInMatrix } from "./DealInMatrix";
import type { PlayerStats } from "./PlayerStats";
import type { ScoreTrendPoint } from "./ScoreTrendPoint";

export type CareerStats = { playerNames: Array<string>, games: number, averagePlacement: number | null, stats: PlayerStats, placementDistribution: Array<CountBucket>, scoreTrend: Array<ScoreTrendPoint>, dealInMatrix: DealInMatrix, };
