// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrawReason = { "type": "exhaustive" } | { "type": "nineTerminals" } | { "type": "fourRiichi" } | { "type": "tripleRon" } | { "type": "fourKans" } | { "type": "fourWinds" } | { "type": "nagashiMangan" } | { "type": "other", code: string, };
