// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DealInMatrix } from "./DealInMatrix";
import type { Kyoku } from "./Kyoku";
import type { PlayerSummary } from "./PlayerSummary";
import type { Ruleset } from "./Ruleset";

export type GameDetail = { logId: string, rules: Ruleset, players: Array<PlayerSummary>, kyoku: Array<Kyoku>, dealInMatrix: DealInMatrix, };
