// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameListItem } from "./GameListItem";

export type GameListPage = { items: Array<GameListItem>, page: number, hasNext: boolean, };
