// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameListPlayer } from "./GameListPlayer";
import type { Ruleset } from "./Ruleset";

export type GameListItem = { logId: string, addedAt: number, rules: Ruleset, players: Array<GameListPlayer>, };
