// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrawReason } from "./DrawReason";
import type { WinResult } from "./WinResult";

export type KyokuResult = { "type": "win", wins: Array<WinResult>, } | { "type": "draw", reason: DrawReason, tenpai_seats: Array<number>, score_deltas: Array<number>, };
