// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KyokuResult } from "./KyokuResult";
import type { TurnEvent } from "./TurnEvent";

export type Kyoku = { roundIndex: number, bakaze: number, kyokuNumber: number, honba: number, riichiSticks: number, dealer: number, startScores: Array<number>, endScores: Array<number>, startHands: Array<Array<number>>, doraIndicators: Array<number>, events: Array<TurnEvent>, result: KyokuResult, };
