// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BonusStats } from "./BonusStats";
import type { CallStats } from "./CallStats";
import type { CountBucket } from "./CountBucket";
import type { PlayerRates } from "./PlayerRates";
import type { YakuCount } from "./YakuCount";

export type PlayerStats = { hands: number, wins: number, tsumoWins: number, ronWins: number, dealIns: number, riichi: number, dealerHands: number, dealerRepeats: number, exhaustiveDraws: number, tenpaiDraws: number, notenDraws: number, calledHands: number, calls: CallStats, bonuses: BonusStats, rates: PlayerRates, yakuFrequency: Array<YakuCount>, hanDistribution: Array<CountBucket>, fuDistribution: Array<CountBucket>, handValueDistribution: Array<CountBucket>, };
