// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerStats } from "./PlayerStats";

export type PlayerSummary = { seat: number, name: string, rankId: number, rank: string, rating: number, sex: string, finalScore: number | null, uma: number | null, placement: number | null, stats: PlayerStats, };
