// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerRates = { winRate: number, tsumoWinRate: number, ronWinRate: number, tsumoShare: number, ronShare: number, dealInRate: number, riichiRate: number, callRate: number, dealerRepeatRate: number, tenpaiRate: number, };
