// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameDetail } from "./GameDetail";
import type { PublicGameOwner } from "./PublicGameOwner";

export type PublicGameDetail = { game: GameDetail, owner: PublicGameOwner, };
