// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Ruleset = { rawType: number, lobby: string, test: boolean, akaDora: boolean, kuitan: boolean, hanchan: boolean, sanma: boolean, fast: boolean, table: string, };
