// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallKind } from "./CallKind";

export type TurnEvent = { "type": "Draw", seat: number, tile: number, } | { "type": "Discard", seat: number, tile: number, tsumogiri: boolean, } | { "type": "Call", seat: number, kind: CallKind, tiles: Array<number>, from_seat: number, } | { "type": "Riichi", seat: number, } | { "type": "NewDora", tile: number, };
