// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Yaku } from "./Yaku";

export type WinResult = { winner: number, fromSeat: number, tsumo: boolean, fu: number, han: number, points: number, limit: number, winningTiles: Array<number>, wait: number, yaku: Array<Yaku>, doraIndicators: Array<number>, scoreDeltas: Array<number>, };
